[tool.isort]
py_version = 311
profile = 'black'
src_paths = ['.']
length_sort = true
multi_line_output = 1
import_heading_firstparty = 'Project'
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
